# Generated by Django 5.0.6 on 2024-05-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_manager'),
        ('userAccount', '0003_alter_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='manager_manages_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
